version: 0.2

phases:
  install:
    commands:
      - echo "Installing PHP..."
      - sudo dnf install -y php php-cli php-common php-mbstring php-xml
      - php -v  # Verify installed version
  pre_build:
    commands:
      - echo "Pre-build phase"
  build:
    commands:
      - echo "Build phase"
  post_build:
    commands:
      - echo "Post-build phase"

artifacts:
  files:
    - '**/*'
